version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis port to host (optional)
    command: redis-server --requirepass "your_redis_password"  # Optional: Add password
    volumes:
      - redis-data:/data  # Persist Redis data

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_redis_password
      - MYSQL_HOST=mysql
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_DB=myapp_db
    volumes:
      - ./app:/app

volumes:
  redis-data:
  mysql-data: