services:
  redis:
    image: redis:latest
    container_name: demo-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass "your_redis_password"
    volumes:
      - redis-data:/data

  mysql:
    container_name: airportbase
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: airportbase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: demo-backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=demo-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_redis_password
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=airportbase
    volumes:
      - ./app:/app

volumes:
  redis-data:
  mysql-data: